# Dictionary mapping country codes to full country names
countries = {
    'US': 'United States',
    'CA': 'Canada',
    'GB': 'United Kingdom',
    'FR': 'France',
    'DE': 'Germany',
    'IT': 'Italy',
    'ES': 'Spain',
    'RU': 'Russia',
    'CN': 'China',
    'JP': 'Japan',
    'KR': 'South Korea',
    'IN': 'India',
    'BR': 'Brazil',
    'MX': 'Mexico',
    'ZA': 'South Africa',
    'AU': 'Australia',
    'NZ': 'New Zealand',
    'AR': 'Argentina',
    'CL': 'Chile',
    'CO': 'Colombia',
    'SE': 'Sweden',
    'NO': 'Norway',
    'DK': 'Denmark',
    'FI': 'Finland',
    'NL': 'Netherlands',
    'BE': 'Belgium',
    'PT': 'Portugal',
    'GR': 'Greece',
    'PL': 'Poland',
    'HU': 'Hungary',
    'RO': 'Romania',
    'IL': 'Israel',
    'TR': 'Turkey',
    'EG': 'Egypt',
    'SA': 'Saudi Arabia',
    'VN': 'Vietnam',
    'TH': 'Thailand',
    'ID': 'Indonesia',
    'MY': 'Malaysia',
    'SG': 'Singapore',
    'PH': 'Philippines',
    'AE': 'United Arab Emirates',
}
